# Generated by Django 3.0.8 on 2020-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('carousel_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carousel_url', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(max_length=100)),
                ('carousel_rank', models.IntegerField()),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_carousel',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('goods_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=200)),
                ('goods_intro', models.CharField(max_length=200)),
                ('goods_cover_img', models.CharField(max_length=200)),
                ('goods_carousel', models.CharField(max_length=500)),
                ('goods_detail_content', models.TextField()),
                ('original_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('stock_num', models.IntegerField()),
                ('tag', models.CharField(max_length=20)),
                ('goods_sell_status', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('create_user', models.IntegerField()),
                ('update_time', models.DateField(auto_now_add=True)),
                ('update_user', models.IntegerField()),
            ],
            options={
                'db_table': 'mall_goods_info',
            },
        ),
    ]
