# Generated by Django 3.0.8 on 2020-08-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsinfo',
            table='goods_info',
        ),
    ]
