# Generated by Django 3.0.8 on 2020-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200803_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=20)),
                ('default_flag', models.IntegerField()),
                ('province_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('region_name', models.CharField(max_length=200)),
                ('detail_address', models.CharField(max_length=200)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
