# Generated by Django 3.0.8 on 2020-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='city_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='detail_address',
            new_name='addressDetail',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='province_name',
            new_name='areaCode',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='region_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='user_name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='user_phone',
            new_name='tel',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='default_flag',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='county',
            field=models.CharField(default='西城区', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='id',
            field=models.CharField(default='1596451104360000', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='isDefault',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='root', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postalCode',
            field=models.CharField(default='345434', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='北京市', max_length=200),
            preserve_default=False,
        ),
    ]
