# Generated by Django 3.0.8 on 2020-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_useraddress_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
