# Generated by Django 3.0.8 on 2020-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_goodscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
