# Generated by Django 3.0.8 on 2020-08-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_orderinfo_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='carousel_1',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='carousel_3',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
