# Generated by Django 3.0.8 on 2020-08-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_goodsinfo_goods_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategory',
            old_name='carousel_3',
            new_name='carousel_2',
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='carousel_small',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
