# Generated by Django 3.0.8 on 2020-08-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_auto_20200804_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='selling_num',
            field=models.IntegerField(default=89845),
        ),
    ]
