# Generated by Django 3.0.8 on 2020-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_goodsinfo_selling_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='selling_num',
            field=models.IntegerField(default=0),
        ),
    ]
