# Generated by Django 3.0.8 on 2020-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_remove_goodsinfo_selling_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='selling_num',
            field=models.IntegerField(default=0),
        ),
    ]
