# Generated by Django 3.0.8 on 2020-08-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_goodsinfo_selling_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTheme',
            fields=[
                ('theme_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('theme_pic', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'goods_theme',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_theme_id',
            field=models.IntegerField(default=0),
        ),
    ]
