# Generated by Django 3.0.8 on 2020-08-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_goodstheme_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstheme',
            name='theme_pic_small',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
