# Generated by Django 3.0.8 on 2020-08-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_goodstheme_theme_pic_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
