# Generated by Django 3.0.8 on 2020-08-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0022_shoppingcart_goods_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='goods_name',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
