# Generated by Django 3.0.8 on 2020-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_orderitem_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
