# Generated by Django 3.0.8 on 2020-08-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
